#!/bin/bash

export PYTHONPATH=$CERESDEVDIR:$PYTHONPATH

sleep_time=$1 # in seconds
shift

while (true)
do
    python $CERESDEVDIR/ceres/launch_jobs.py $*
    echo "Last submission:" $(date)
    sleep ${sleep_time}
done